### ISSUE TITLE
Fails with namespaced models

### ISSUE THREAD

**Issue by Kriechi** [7even/active_record-annotate#4]
Assuming the following structure:
```
app/models/foo.rb
app/models/foo/bar.rb
app/models/foo/goo.rb
```

In order for the annotation to work, the classes inside `app/models/foo/` must be declared as:
`class Foo::Bar` and `class Foo::Goo`. 
But now Rails seems to have a problem with it and can't find it anymore: 
```
[...]/lib/active_support/dependencies.rb:495:in `load_missing_constant': Unable to
autoload constant Bar, expected [...]/app/models/foo/bar.
rb to define it (LoadError)
```

I have the following in my `config/application.rb`:
```
config.autoload_paths += %W(#{config.root}/app/models/foo)
```

If I remove the autoload line, I get: `uninitialized constant Bar (NameError)`.

Can I fix this in my Rails app, or is it a bug?
I guess this is somehow the problem - or at least the source of my confusion: https://github.com/7even/active_record-annotate/blob/master/lib/active_record/annotate.rb#L58-61

**Comment by 7even** [comment]
> In order for the annotation to work, the classes inside app/models/foo/ must be declared as:
> class Foo::Bar and class Foo::Goo.

Yep.

> But now Rails seems to have a problem with it and can't find it anymore

Do I get it right that you are declaring `class Bar` inside `app/models/foo/bar.rb`? If so, this breaks rails' file naming conventions: your class needs to be called `Foo::Bar` (that would also free you from appending `app/models/foo` to autoload paths).

This gem relies on these conventions to find a model class for each file found under `app/models`.

**Comment by Kriechi** [comment]
Thanks - seems I have to fix my Rails app then.
