### ISSUE TITLE
Initializer does not work out-of-the-box

### ISSUE THREAD

**Issue by Kriechi** [7even/active_record-annotate#5]
If I add this gem in my `development` group, then the initializer will throw an error, because the gem is not loaded. Workaround: safe-guard the initializer code to only run if `Rails.development?` or similar...

**Comment by 7even** [comment]
I made a quick fix in #6, please check if it works for you:

``` ruby
# Gemfile
group :development do
  gem 'active_record-annotate', github: '7even/active_record-annotate', branch: 'initializer_fix'
end
```
