### ISSUE TITLE
Annotation overrides magic comments

### ISSUE THREAD

**Issue by Morozzzko** [7even/active_record-annotate#8]
We expect generated annotations not to override existing magic comments.

If you use `# frozen_string_literal: true` or any other magic comment, the gem will override it, causing unwanted diffs in the code.

Expected behavior: the gem adds annotation **after** magic comments

**Comment by 7even** [comment]
Actually the gem handles `# encoding: utf-8` comments [correctly](https://github.com/7even/active_record-annotate/blob/261b8cb64fcae203fe083481dd2eba5435040546/lib/active_record/annotate/file.rb#L13-L16); we just need to make it recognize [other types of magic comments](https://idiosyncratic-ruby.com/58-magic-instructions.html).

**Comment by Morozzzko** [comment]
Seems to work, thank you!

**Comment by 7even** [comment]
@Morozzzko released in `0.4.3`.
